---
abstract: 'Perl wrapper for the Songkick API'
author:
  - 'Dave Cross <dave@mag-sol.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Songkick
provides:
  Net::Songkick:
    file: lib/Net/Songkick.pm
    version: 0.04
  Net::Songkick::Artist:
    file: lib/Net/Songkick/Artist.pm
  Net::Songkick::Country:
    file: lib/Net/Songkick/Country.pm
  Net::Songkick::Event:
    file: lib/Net/Songkick/Event.pm
  Net::Songkick::Location:
    file: lib/Net/Songkick/Location.pm
  Net::Songkick::MetroArea:
    file: lib/Net/Songkick/MetroArea.pm
  Net::Songkick::Performance:
    file: lib/Net/Songkick/Performance.pm
  Net::Songkick::SetList:
    file: lib/Net/Songkick/SetList.pm
  Net::Songkick::SetListItem:
    file: lib/Net/Songkick/SetListItem.pm
  Net::Songkick::Venue:
    file: lib/Net/Songkick/Venue.pm
requires:
  DateTime::Format::Strptime: 0
  LWP::UserAgent: 0
  Moose: 0
  XML::LibXML: 0
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
